const uint8_t sound_mario[]=
{
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(E5, 4),

		MAKE_NOTE(G5, 4),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(G4, 4),
		MAKE_NOTE(REST, 4),

		MAKE_NOTE(C5, 6),
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(E4, 6),

		MAKE_NOTE(A4, 4),
		MAKE_NOTE(B4, 4),
		MAKE_NOTE(AS4, 2),
		MAKE_NOTE(A4, 4),

		MAKE_NOTE(G4, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(A5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(G5, 2),

		MAKE_NOTE(REST, 2),
		MAKE_NOTE(E5, 4),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 2),
		MAKE_NOTE(B4, 6),

		MAKE_NOTE(C5, 6),
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(E4, 6),

		MAKE_NOTE(A4, 4),
		MAKE_NOTE(B4, 4),
		MAKE_NOTE(AS4, 2),
		MAKE_NOTE(A4, 4),

		MAKE_NOTE(G4, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(A5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(G5, 2),

		MAKE_NOTE(REST, 2),
		MAKE_NOTE(E5, 4),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 2),
		MAKE_NOTE(B4, 6),

		MAKE_NOTE(REST, 4),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(FS5, 2),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(DS5, 4),
		MAKE_NOTE(E5, 2),

		MAKE_NOTE(REST, 2),
		MAKE_NOTE(GS4, 2),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 2),

		MAKE_NOTE(REST, 4),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(FS5, 2),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(DS5, 4),
		MAKE_NOTE(E5, 2),

		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C6, 4),
		MAKE_NOTE(C6, 2),
		MAKE_NOTE(C6, 8),

		MAKE_NOTE(REST, 4),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(FS5, 2),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(DS5, 4),
		MAKE_NOTE(E5, 2),

		MAKE_NOTE(REST, 2),
		MAKE_NOTE(GS4, 2),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 2),

		MAKE_NOTE(REST, 4),
		MAKE_NOTE(DS5, 4),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(D5, 6),

		MAKE_NOTE(C5, 8),
		MAKE_NOTE(REST, 8),

		MAKE_NOTE(REST, 4),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(FS5, 2),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(DS5, 4),
		MAKE_NOTE(E5, 2),

		MAKE_NOTE(REST, 2),
		MAKE_NOTE(GS4, 2),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 2),

		MAKE_NOTE(REST, 4),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(FS5, 2),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(DS5, 4),
		MAKE_NOTE(E5, 2),

		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C6, 4),
		MAKE_NOTE(C6, 2),
		MAKE_NOTE(C6, 8),

		MAKE_NOTE(REST, 4),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(FS5, 2),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(DS5, 4),
		MAKE_NOTE(E5, 2),

		MAKE_NOTE(REST, 2),
		MAKE_NOTE(GS4, 2),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 2),

		MAKE_NOTE(REST, 4),
		MAKE_NOTE(DS5, 4),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(D5, 6),

		MAKE_NOTE(C5, 8),
		MAKE_NOTE(REST, 8),


		MAKE_NOTE(C5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 4),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(G4, 8),

		MAKE_NOTE(C5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 2),
		MAKE_NOTE(E5, 2),

		MAKE_NOTE(REST, 8), // <=== duplicate
		MAKE_NOTE(REST, 8),

		MAKE_NOTE(C5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 4),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(G4, 8),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(E5, 4),

		MAKE_NOTE(G5, 4),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(G4, 4),
		MAKE_NOTE(REST, 4),

		MAKE_NOTE(C5, 6),
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(E4, 6),

		MAKE_NOTE(A4, 4),
		MAKE_NOTE(B4, 4),
		MAKE_NOTE(AS4, 2),
		MAKE_NOTE(A4, 4),

		MAKE_NOTE(G4, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(A5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(G5, 2),

		MAKE_NOTE(REST, 2),
		MAKE_NOTE(E5, 4),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 2),
		MAKE_NOTE(B4, 6),

		MAKE_NOTE(C5, 6),
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(E4, 6),

		MAKE_NOTE(A4, 4),
		MAKE_NOTE(B4, 4),
		MAKE_NOTE(AS4, 2),
		MAKE_NOTE(A4, 4),

		MAKE_NOTE(G4, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(A5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(G5, 2),

		// measure 42
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(E5, 4),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 2),
		MAKE_NOTE(B4, 6),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(GS4, 4),

		MAKE_NOTE(A4, 2),
		MAKE_NOTE(F5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(A4, 8),

		MAKE_NOTE(B4, 2),
		MAKE_NOTE(A5, 8),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(F5, 2),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(G4, 8),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(GS4, 4),

		MAKE_NOTE(A4, 2),
		MAKE_NOTE(F5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(A4, 8),

		MAKE_NOTE(B4, 2),
		MAKE_NOTE(F5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(D5, 2),

		//C5, 16,
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(E4, 4),
		MAKE_NOTE(E4, 2),
		MAKE_NOTE(C4, 8),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(GS4, 4),

		// measure 52
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(F5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(A4, 8),

		MAKE_NOTE(B4, 2),
		MAKE_NOTE(A5, 8),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(F5, 2),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(G4, 8),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(GS4, 4),

		// 56

		MAKE_NOTE(A4, 2),
		MAKE_NOTE(F5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(A4, 8),

		MAKE_NOTE(B4, 2),
		MAKE_NOTE(F5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(D5, 2),

		//C5, 16,
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(E4, 4),
		MAKE_NOTE(E4, 2),
		MAKE_NOTE(C4, 8),

		MAKE_NOTE(C5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 4),

		// 60

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(G4, 8),

		MAKE_NOTE(C5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 2),
		MAKE_NOTE(E5, 2),

		MAKE_NOTE(REST, 8), // <=== duplicate
		MAKE_NOTE(REST, 8),

		MAKE_NOTE(C5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(D5, 4),

		// 64

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(G4, 8),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(REST, 2),
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(E5, 4),

		MAKE_NOTE(G5, 4),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(G4, 4),
		MAKE_NOTE(REST, 4),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(GS4, 4),

		// 68

		MAKE_NOTE(A4, 2),
		MAKE_NOTE(F5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(A4, 8),

		MAKE_NOTE(B4, 2),
		MAKE_NOTE(A5, 8),
		MAKE_NOTE(G5, 2),
		MAKE_NOTE(F5, 2),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(G4, 8),

		MAKE_NOTE(E5, 2),
		MAKE_NOTE(C5, 4),
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(REST, 4),
		MAKE_NOTE(GS4, 4),

		// 72

		MAKE_NOTE(A4, 2),
		MAKE_NOTE(F5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(A4, 8),

		MAKE_NOTE(B4, 2),
		MAKE_NOTE(F5, 4),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(F5, 2),
		MAKE_NOTE(E5, 2),
		MAKE_NOTE(D5, 2),

		//C5, 16,
		MAKE_NOTE(C5, 2),
		MAKE_NOTE(E4, 4),
		MAKE_NOTE(E4, 2),
		MAKE_NOTE(C4, 8),

		MAKE_NOTE(C5, 6),
		MAKE_NOTE(G4, 6),
		MAKE_NOTE(E4, 4),

		// 72

		MAKE_NOTE(A4, 2),
		MAKE_NOTE(B4, 2),
		MAKE_NOTE(A4, 2),
		MAKE_NOTE(GS4, 2),
		MAKE_NOTE(AS4, 2),
		MAKE_NOTE(GS4, 2),

		//G4, 16,
		MAKE_NOTE(G4, 2),
		MAKE_NOTE(D4, 2),
		MAKE_NOTE(E4, 8), // <=== duplicate
		MAKE_NOTE(E4, 4),

		MAKE_NOTE(REST, 4),
};


